site_name: OntoBDC Documentation
site_description: Documentation for OntoBDC - Ontology-Based Data Capabilities
site_author: Elias M. P. Junior

repo_url: https://github.com/eliasmpjunior/ontobdc-stack
repo_name: ontobdc-stack

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list

nav:
  - Home: index.md
  - Architecture:
      - Introduction: architecture/index.md
  - Specifications:
      - Overview: spec/index.md
